server:
    port: 8089
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: springboot-web-wy
    zipkin.base-url: http://localhost:9411/
    sleuth.sampler.probability: 1.0
